pool:
  name: Azure Pipelines
  demands:
  - npm
  - azureps

steps:
- task: Npm@1
  displayName: 'npm install'
  inputs:
    workingDir: .
    verbose: false

- task: Npm@1
  displayName: 'npm custom'
  inputs:
    command: custom
    workingDir: .
    verbose: false
    customCommand: 'run build'

- task: AzureFileCopy@2
  displayName: 'AzureBlob File Copy'
  inputs:
    SourcePath: dist/AngularDemo
    azureSubscription: 'Visual Studio Enterprise'
    Destination: AzureBlob
    storage: dotnetthoughts
    ContainerName: '$web'